"""empty message

Revision ID: 6185c23f4cfc
Revises: c21aa9cb2941
Create Date: 2021-10-09 11:15:40.794307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6185c23f4cfc'
down_revision = 'c21aa9cb2941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
