"""Add duplication table

Revision ID: ddeb96a13f9e
Revises: 81d1aa645701
Create Date: 2023-09-29 20:07:18.848777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddeb96a13f9e'
down_revision = '81d1aa645701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplication',
    sa.Column('duplication_id', sa.String(), nullable=True),
    sa.Column('book_uuid_1', sa.String(), nullable=False),
    sa.Column('book_uuid_2', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_uuid_1'], ['books.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_uuid_2'], ['books.uuid'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_uuid_1', 'book_uuid_2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('duplication')
    # ### end Alembic commands ###
