"""Add ahash

Revision ID: 81d1aa645701
Revises: d1a1c7e12e70
Create Date: 2023-09-29 19:15:11.775414

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '81d1aa645701'
down_revision = 'd1a1c7e12e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('ahash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'ahash')
    # ### end Alembic commands ###
