"""empty message

Revision ID: 1d7a2a530d9f
Revises: 43b53bf68b39
Create Date: 2024-05-05 09:31:46.243400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7a2a530d9f'
down_revision = '43b53bf68b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_book_to_author_author_id'), 'book_to_author', ['author_id'], unique=False)
    op.create_index(op.f('ix_book_to_author_book_uuid'), 'book_to_author', ['book_uuid'], unique=False)
    op.create_index(op.f('ix_books_publisher_id'), 'books', ['publisher_id'], unique=False)
    op.create_index(op.f('ix_tag_to_book_book_uuid'), 'tag_to_book', ['book_uuid'], unique=False)
    op.create_index(op.f('ix_tag_to_book_tags_id'), 'tag_to_book', ['tags_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_to_book_tags_id'), table_name='tag_to_book')
    op.drop_index(op.f('ix_tag_to_book_book_uuid'), table_name='tag_to_book')
    op.drop_index(op.f('ix_books_publisher_id'), table_name='books')
    op.drop_index(op.f('ix_book_to_author_book_uuid'), table_name='book_to_author')
    op.drop_index(op.f('ix_book_to_author_author_id'), table_name='book_to_author')
    # ### end Alembic commands ###
