"""fix_column_name_typos_chached_to_cached_is_shered_to_is_shared

Revision ID: 40f414b33f9d
Revises: 7d7ba6b08aaa
Create Date: 2026-02-10 15:19:56.745885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f414b33f9d'
down_revision = '7d7ba6b08aaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # booksテーブルのカラム名タイポを修正
    op.alter_column('books', 'chached', new_column_name='cached')
    op.alter_column('books', 'is_shered', new_column_name='is_shared')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # カラム名を元に戻す
    op.alter_column('books', 'cached', new_column_name='chached')
    op.alter_column('books', 'is_shared', new_column_name='is_shered')
    # ### end Alembic commands ###
