version: "3"
services:
  api:
    build: ./api
    volumes:
      # キャッシュの作成場所
      - ./data/book_cache:/opt/data/book_cache/
      # ライブラリ
      - ./data/book_library:/opt/data/book_library/
      # ZIPのインポート監視フォルダ
      - ./data/book_send:/opt/data/book_send/
      # ZIPのエクスポート先
      - ./data/book_export:/opt/data/book_export/
      # 失敗したZIP
      - ./data/book_fail:/opt/data/book_fail/
      # データベースやログファイル
      - ./data/app_data:/opt/data/app_data/
    environment:
      APP_ROOT: "/opt/app/"
      DATA_ROOT: "/opt/data/"
      SQLALCHEMY_DATABASE_URL: "postgresql://postgres:password@db:5432/mydatabase"
    restart: always
  web:
    build: ./web
    volumes:
      # Nginxのログ
      - ./data/nginx:/var/log/nginx/
    ports:
      - 0.0.0.0:80:80
    restart: always
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      # データベース
      - ./data/postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password