/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User Info */
        get: operations["get_current_user_info_api_users_me__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login For Access Token */
        post: operations["login_for_access_token_api_auth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Api Auth Setup */
        post: operations["api_auth_setup_api_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Validate Token */
        get: operations["validate_token_api_auth_validate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Libraries */
        get: operations["list_libraries_api_libraries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Books */
        get: operations["search_books_api_books_get"];
        /** Update Books */
        put: operations["update_books_api_books_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Book */
        delete: operations["delete_book_api_books__book_uuid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_uuid}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 本のZipファイルダウンロード
         * @description 指定された本のZipファイルをダウンロードする
         */
        get: operations["download_book_api_books__book_uuid__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/books/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** キャッシュサイズの確認 */
        get: operations["get_media_books_cache_media_books_cache_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/books/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 重複本の確認 */
        get: operations["get_media_books_duplicate_media_books_duplicate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/books/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サムネイル取得 */
        get: operations["get_media_books_uuid_media_books__uuid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/books/{uuid}/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ページ取得 */
        get: operations["media_books_uuid_page_media_books__uuid___page__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 本の一括変換タスク実行 */
        patch: operations["patch_media_books__media_books_patch"];
        trace?: never;
    };
    "/media/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * ライブラリのロードやエクスポート
         * @description - state=load ライブラリのロード
         *     - state=export ライブラリのエクスポート
         */
        patch: operations["patch_media_library_media_library_patch"];
        trace?: never;
    };
    "/api/books/{uuid}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Book Tags
         * @description 指定した書籍のタグ一覧を取得する
         */
        get: operations["get_book_tags_api_books__uuid__tags_get"];
        put?: never;
        /**
         * Add Book Tag
         * @description 指定した書籍にタグを追加する
         */
        post: operations["add_book_tag_api_books__uuid__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{uuid}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Book Tag
         * @description 指定した書籍から指定したタグを削除する（ボディなし）
         */
        delete: operations["remove_book_tag_api_books__uuid__tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tags
         * @description ユーザーが所有する書籍に関連付けられているタグの一覧を取得する
         */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Authors */
        get: operations["list_authors_api_authors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Author */
        patch: operations["update_author_api_authors_patch"];
        trace?: never;
    };
    "/api/books/{book_uuid}/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Book Author */
        post: operations["add_book_author_api_books__book_uuid__authors_post"];
        /** Remove Book Author */
        delete: operations["remove_book_author_api_books__book_uuid__authors_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/user-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 本のユーザデータ（レート）を一括更新 */
        put: operations["change_user_data_api_books_user_data_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 開いているページ、読んだ回数の管理
         * @description - 本を開いたとき status=open, page=0
         *     - 本を途中で閉じた時 status=pause, page=5
         *     - 本を読み終わったとき status=close, page=None
         */
        patch: operations["signal_book_status_api_books_user_data_patch"];
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Version
         * @description 初期化済みか判定用
         */
        get: operations["get_version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Settings
         * @description システム設定一覧を取得
         *
         *     - 管理者: 全設定を取得可能
         *     - 一般ユーザー: is_public=true の設定のみ取得可能
         *     - category パラメータでフィルタリング可能
         */
        get: operations["list_settings_api_system_settings_get"];
        put?: never;
        /**
         * Create Setting
         * @description 新規設定を作成（管理者のみ）
         */
        post: operations["create_setting_api_system_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Setting By Key
         * @description 個別設定を取得
         *
         *     - 管理者: 全設定を取得可能
         *     - 一般ユーザー: is_public=true の設定のみ取得可能
         */
        get: operations["get_setting_by_key_api_system_settings__key__get"];
        /**
         * Update Setting
         * @description 設定を更新（管理者のみ）
         */
        put: operations["update_setting_api_system_settings__key__put"];
        post?: never;
        /**
         * Delete Setting
         * @description 設定を削除（管理者のみ）
         */
        delete: operations["delete_setting_api_system_settings__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/settings/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Update Settings
         * @description 設定を一括更新（管理者のみ）
         */
        post: operations["bulk_update_settings_api_system_settings_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/settings/category/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings By Category Endpoint
         * @description カテゴリ別に設定を取得（型変換済みの値）
         *
         *     - 管理者: 全設定を取得可能
         *     - 一般ユーザー: is_public=true の設定のみ取得可能
         */
        get: operations["get_settings_by_category_endpoint_api_system_settings_category__category__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/settings/all/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Settings Values
         * @description 全設定を取得（型変換済みの値）
         *
         *     - 管理者: 全設定を取得可能
         *     - 一般ユーザー: is_public=true の設定のみ取得可能
         */
        get: operations["get_all_settings_values_api_system_settings_all_values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthValidateResponse */
        AuthValidateResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
            /** Username */
            username: string;
            /** Is Admin */
            is_admin: boolean;
        };
        /** AuthorGet */
        AuthorGet: {
            /** Id */
            id?: number | null;
            /** Name */
            name?: string | null;
            /**
             * Isfavorite
             * @default false
             */
            isFavorite: boolean;
        };
        /** Body_login_for_access_token_api_auth_post */
        Body_login_for_access_token_api_auth_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** BookAuthorDelete */
        BookAuthorDelete: {
            /** Authorid */
            authorId: number;
        };
        /** BookAuthorPost */
        BookAuthorPost: {
            /** Authorid */
            authorId?: number | null;
            /** Authorname */
            authorName?: string | null;
        };
        /** BookAuthors */
        BookAuthors: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Isfavorite
             * @default false
             */
            isFavorite: boolean;
        };
        /** BookBase */
        BookBase: {
            /** Uuid */
            uuid: string;
            /** Userid */
            userId: string;
            /** Title */
            title?: string | null;
            /** Authors */
            authors: components["schemas"]["BookAuthors"][];
            publisher: components["schemas"]["BookPublisher"];
            /** Isshered */
            isShered: boolean;
            /** Chached */
            chached: boolean;
            /** Libraryid */
            libraryId: number;
            /** Genreid */
            genreId?: string | null;
            /** Tags */
            tags: components["schemas"]["BookTag"][];
            /** Size */
            size: number;
            /** Page */
            page: number;
            /** Sha1 */
            sha1: string;
            /** Importfilename */
            importFileName: string;
            /**
             * Adddate
             * Format: date-time
             */
            addDate: string;
            /**
             * Filedate
             * Format: date-time
             */
            fileDate: string;
            userData: components["schemas"]["BookUserDataBase"];
        };
        /** BookCacheCreate */
        BookCacheCreate: {
            /** Uuid */
            uuid: string;
            /** Height */
            height: number;
        };
        /** BookGet */
        BookGet: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Count */
            count: number;
            /** Rows */
            rows: components["schemas"]["BookBase"][];
        };
        /** BookPublisher */
        BookPublisher: {
            /**
             * Name
             * @default
             */
            name: string | null;
            /** Id */
            id?: number | null;
        };
        /** BookPut */
        BookPut: {
            /** Uuids */
            uuids: string[];
            /** Seriesno */
            seriesNo?: number | null;
            /** Series */
            series?: string | null;
            /** Author */
            author?: string | null;
            /** Title */
            title?: string | null;
            /** Publisher */
            publisher?: string | null;
            /** Genre */
            genre?: string | null;
            /** Libraryid */
            libraryId?: number | null;
        };
        /** BookTag */
        BookTag: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** BookUserDataBase */
        BookUserDataBase: {
            /** Lastopendate */
            lastOpenDate?: string | null;
            /** Readtimes */
            readTimes?: number | null;
            /** Openpage */
            openPage?: number | null;
            /** Rate */
            rate?: number | null;
        };
        /** BookUserMetaDataPatch */
        BookUserMetaDataPatch: {
            /** Uuids */
            uuids: string[];
            /** Page */
            page?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "close" | "pause";
        };
        /** BookUserMetaDataPut */
        BookUserMetaDataPut: {
            /** Uuids */
            uuids: string[];
            /** Rate */
            rate?: number | null;
        };
        /** GetLibrary */
        GetLibrary: {
            /** Count */
            count: number;
            /** Name */
            name: string;
            /** Id */
            id: number;
            /** Userid */
            userId: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LibraryPatch */
        LibraryPatch: {
            /** @default load */
            state: components["schemas"]["LibraryPatchEnum"];
        };
        /**
         * LibraryPatchEnum
         * @enum {string}
         */
        LibraryPatchEnum: "export" | "load" | "export_uuid" | "fixmetadata" | "sim_all" | "rule" | "thumbnail_recreate";
        /** PatchAuthor */
        PatchAuthor: {
            /** Authorid */
            authorId: number;
            /** Isfavorite */
            isFavorite: boolean;
        };
        /**
         * SystemSettingBulkUpdateSchema
         * @description 一括更新用
         */
        SystemSettingBulkUpdateSchema: {
            /** Settings */
            settings: {
                [key: string]: string;
            };
        };
        /**
         * SystemSettingCreateSchema
         * @description 設定作成用
         */
        SystemSettingCreateSchema: {
            /** Key */
            key: string;
            /** Value */
            value: string;
            /**
             * Datatype
             * @default string
             */
            dataType: string;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Ispublic
             * @default false
             */
            isPublic: boolean;
        };
        /**
         * SystemSettingSchema
         * @description システム設定項目
         */
        SystemSettingSchema: {
            /** Key */
            key: string;
            /** Value */
            value: string;
            /** Datatype */
            dataType: string;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Ispublic
             * @default false
             */
            isPublic: boolean;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Updatedby */
            updatedBy?: string | null;
        };
        /**
         * SystemSettingValueSchema
         * @description 設定値のみ（更新用）
         */
        SystemSettingValueSchema: {
            /** Value */
            value: string;
        };
        /**
         * SystemSettingsListResponse
         * @description 設定一覧レスポンス
         */
        SystemSettingsListResponse: {
            /** Settings */
            settings: components["schemas"]["SystemSettingSchema"][];
            /** Total */
            total: number;
        };
        /**
         * TagCreate
         * @description タグ作成スキーマ
         */
        TagCreate: {
            /** Name */
            name: string;
        };
        /** TokenRFC6749Response */
        TokenRFC6749Response: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UserGet */
        UserGet: {
            /** Id */
            id?: string | null;
            /** Isadmin */
            isAdmin: boolean;
        };
        /** UserPost */
        UserPost: {
            /** Id */
            id?: string | null;
            /** Password */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Version */
        Version: {
            /** Initialized */
            initialized: boolean;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGet"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPost"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_users_me__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGet"];
                };
            };
        };
    };
    login_for_access_token_api_auth_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_api_auth_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRFC6749Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_auth_setup_api_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPost"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_token_api_auth_validate_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthValidateResponse"];
                };
            };
        };
    };
    list_libraries_api_libraries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetLibrary"][];
                };
            };
        };
    };
    search_books_api_books_get: {
        parameters: {
            query?: {
                uuid?: string | null;
                fileNameLike?: string | null;
                cached?: boolean | null;
                authorLike?: string | null;
                authorIsFavorite?: boolean | null;
                titleLike?: string | null;
                fullText?: string | null;
                rate?: number | null;
                seriesId?: string | null;
                genreId?: string | null;
                libraryId?: number;
                tag?: string | null;
                state?: string | null;
                limit?: number;
                offset?: number;
                sortKey?: string;
                sortDesc?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookGet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_books_api_books_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BookPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_book_api_books__book_uuid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_book_api_books__book_uuid__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_books_cache_media_books_cache_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_media_books_duplicate_media_books_duplicate_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_books_uuid_media_books__uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    media_books_uuid_page_media_books__uuid___page__get: {
        parameters: {
            query?: {
                height?: number;
            };
            header?: never;
            path: {
                uuid: string;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_media_books__media_books_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCacheCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_media_library_media_library_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_tags_api_books__uuid__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 書籍UUID */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_book_tag_api_books__uuid__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 書籍UUID */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_book_tag_api_books__uuid__tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 書籍UUID */
                uuid: string;
                /** @description タグID */
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_authors_api_authors_get: {
        parameters: {
            query: {
                isFavorite: boolean;
                name?: string | null;
                nameLike?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorGet"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_author_api_authors_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchAuthor"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_book_author_api_books__book_uuid__authors_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookAuthorPost"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_book_author_api_books__book_uuid__authors_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookAuthorDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_user_data_api_books_user_data_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BookUserMetaDataPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_book_status_api_books_user_data_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BookUserMetaDataPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    list_settings_api_system_settings_get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSettingsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_setting_api_system_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemSettingCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSettingSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_setting_by_key_api_system_settings__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSettingSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_setting_api_system_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemSettingValueSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSettingSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_setting_api_system_settings__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_settings_api_system_settings_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemSettingBulkUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_by_category_endpoint_api_system_settings_category__category__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_settings_values_api_system_settings_all_values_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
