/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description ログインしてアクセストークンを取得する
         *
         *     OAuth2 Password Flowに準拠した認証エンドポイント。
         *     ユーザー名とパスワードを送信し、JWTアクセストークンを取得します。
         *
         *     Args:
         *         form_data: OAuth2のフォームデータ（username, password）
         *
         *     Returns:
         *         アクセストークンとトークンタイプ
         *
         *     Raises:
         *         401: ユーザー名またはパスワードが間違っている場合
         */
        post: operations["login_for_access_token_api_auth_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 初期セットアップ
         * @description 初回セットアップで管理者ユーザーを作成する
         *
         *     システムに初めてアクセスする際に使用します。
         *     既にユーザーが存在する場合はエラーを返します。
         *     作成されたユーザーは管理者権限を持ちます。
         *
         *     Args:
         *         user: ユーザー情報（ID、パスワード）
         *
         *     Returns:
         *         作成された管理者ユーザー情報
         *
         *     Raises:
         *         400: ユーザーIDが空、または既に初期化済みの場合
         */
        post: operations["api_auth_setup_api_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * トークン検証
         * @description JWTトークンを検証し、ユーザー情報を返す
         *
         *     認証済みトークンの有効性を確認し、現在のユーザー情報を取得します。
         */
        get: operations["validate_token_api_auth_validate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザー一覧取得
         * @description ユーザー一覧を取得する
         *
         *     管理者権限が必要です。
         */
        get: operations["list_users_api_users_get"];
        put?: never;
        /**
         * ユーザー作成
         * @description 新規ユーザーを作成する
         *
         *     管理者権限が必要です。
         *     作成されたユーザーは非管理者として登録されます。
         *
         *     Args:
         *         user: ユーザー情報（ID、パスワード）
         *
         *     Returns:
         *         作成されたユーザー情報
         *
         *     Raises:
         *         400: ユーザーIDが既に存在する場合
         */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 現在のユーザー情報取得
         * @description 現在ログイン中のユーザー情報を取得する
         *
         *     認証トークンから自身のユーザー情報を取得します。
         */
        get: operations["get_current_user_info_api_users_me__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ライブラリ一覧取得
         * @description ライブラリ一覧を取得する
         *
         *     各ライブラリに含まれる書籍数とともにライブラリ情報を取得します。
         */
        get: operations["list_libraries_api_libraries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 書籍検索
         * @description 書籍を検索する
         *
         *     様々な条件で書籍を検索し、ページネーション形式で結果を返します。
         *     管理者は全ての書籍を、一般ユーザーは自分の書籍と共有された書籍のみを検索できます。
         *
         *     検索条件:
         *     - uuid: 書籍UUID（完全一致）
         *     - fileNameLike: ファイル名（部分一致）
         *     - cached: キャッシュ済みか
         *     - authorLike: 著者名（部分一致）
         *     - authorIsFavorite: お気に入り著者フィルタ
         *     - titleLike: タイトル（部分一致）
         *     - fullText: 全文検索（タイトル、ファイル名、著者名、タグ名）
         *     - rate: 評価（0は未評価）
         *     - tag: タグ名（完全一致）
         *     - sortKey: ソートキー（title, addDate, size, userData.lastOpenDate, authors）
         *     - sortDesc: 降順ソート
         */
        get: operations["search_books_api_books_get"];
        /**
         * 書籍情報一括更新
         * @description 書籍情報を一括更新する
         *
         *     指定されたUUID一覧の書籍に対して、同じ変更を適用します。
         *
         *     更新可能な項目:
         *     - title: タイトル
         *     - series: シリーズ名
         *     - seriesNo: シリーズ番号
         *     - publisher: 出版社名
         *     - genre: ジャンル
         *     - libraryId: ライブラリID
         *
         *     Raises:
         *         404: 指定された書籍が存在しない場合
         */
        put: operations["update_books_api_books_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 書籍削除
         * @description 書籍を削除する
         *
         *     指定された書籍を完全に削除します。
         *     書籍ファイル、ユーザーデータ、データベースレコードが全て削除されます。
         *
         *     Args:
         *         book_uuid: 削除する書籍のUUID
         *
         *     Raises:
         *         404: 指定された書籍が存在しない場合
         */
        delete: operations["delete_book_api_books__book_uuid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_uuid}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 書籍Zipファイルダウンロード
         * @description 指定された本のZipファイルをダウンロードする
         */
        get: operations["download_book_api_books__book_uuid__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/books/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** キャッシュサイズ確認 */
        get: operations["get_media_books_cache_media_books_cache_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/books/duplicate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 重複書籍確認 */
        get: operations["get_media_books_duplicate_media_books_duplicate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/books/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** サムネイル取得 */
        get: operations["get_media_books_uuid_media_books__uuid__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/books/{uuid}/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ページ画像取得 */
        get: operations["media_books_uuid_page_media_books__uuid___page__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 書籍一括変換タスク実行 */
        patch: operations["patch_media_books__media_books_patch"];
        trace?: never;
    };
    "/media/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * ライブラリロード・エクスポート（非推奨）
         * @deprecated
         * @description **[非推奨] このエンドポイントは非推奨です。代わりに POST /api/tasks を使用してください。**
         *
         *     各種バックグラウンドタスクを開始する
         *
         *     state:
         *     - load: ライブラリのロード
         *     - fixmetadata: メタデータの修正
         *     - export: ライブラリのエクスポート
         *     - export_uuid: UUID指定エクスポート
         *     - sim_all: 全体の類似度計算
         *     - rule: ルール適用
         *     - thumbnail_recreate: サムネイル再作成
         *     - integrity_check: 整合性チェック
         */
        patch: operations["patch_media_library_media_library_patch"];
        trace?: never;
    };
    "/api/books/{uuid}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 書籍のタグ一覧取得
         * @description 指定した書籍のタグ一覧を取得する
         *
         *     Raises:
         *         404: 書籍が存在しない、または所有していない場合
         */
        get: operations["get_book_tags_api_books__uuid__tags_get"];
        put?: never;
        /**
         * タグ追加
         * @description 指定した書籍にタグを追加する
         *
         *     タグ名が既に存在する場合は既存のタグを使用し、
         *     存在しない場合は新規作成します。
         *
         *     Raises:
         *         404: 書籍が存在しない、または所有していない場合
         */
        post: operations["add_book_tag_api_books__uuid__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{uuid}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * タグ削除
         * @description 指定した書籍から指定したタグを削除する
         *
         *     Raises:
         *         404: 書籍、タグが存在しない、またはタグが関連付けられていない場合
         */
        delete: operations["remove_book_tag_api_books__uuid__tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * タグ一覧取得
         * @description タグ一覧を取得する
         *
         *     ユーザーが所有する書籍に関連付けられているタグのみを返します。
         */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 著者一覧取得
         * @description 著者一覧を取得する
         *
         *     - name: 完全一致検索
         *     - name_like: 部分一致検索
         *     - is_favorite: お気に入りフィルタ（True/False/None）
         */
        get: operations["list_authors_api_authors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 著者情報更新（旧形式・非推奨）
         * @deprecated
         * @description 著者情報を更新する（旧形式・非推奨）
         *
         *     このエンドポイントは後方互換性のために残されています。
         *     新規実装では PATCH /api/authors/{author_id} を使用してください。
         */
        patch: operations["update_author_api_authors_patch"];
        trace?: never;
    };
    "/api/authors/{author_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 著者詳細取得
         * @description 著者の詳細情報を取得する
         *
         *     - author_id: 著者ID
         */
        get: operations["get_author_api_authors__author_id__get"];
        put?: never;
        post?: never;
        /**
         * 著者削除
         * @description 著者を削除する
         *
         *     書籍に紐づいている著者は削除できません。
         */
        delete: operations["delete_author_api_authors__author_id__delete"];
        options?: never;
        head?: never;
        /**
         * 著者情報更新
         * @description 著者情報を更新する
         *
         *     - name: 著者名
         *     - is_favorite: お気に入り設定
         *     - description: 説明
         */
        patch: operations["update_author_by_id_api_authors__author_id__patch"];
        trace?: never;
    };
    "/api/books/{book_uuid}/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 書籍に著者を追加
         * @description 書籍に著者を追加する
         *
         *     - author_id: 既存の著者IDを指定
         *     - author_name: 著者名を指定（存在しない場合は新規作成）
         */
        post: operations["add_book_author_api_books__book_uuid__authors_post"];
        /**
         * 書籍から著者を削除
         * @description 書籍から著者を削除する
         *
         *     - author_id: 削除する著者ID
         */
        delete: operations["remove_book_author_api_books__book_uuid__authors_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/user-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * レート一括更新
         * @description 書籍のユーザーデータ（レート）を一括更新する
         *
         *     指定された書籍の評価を一括で設定します。
         *
         *     Args:
         *         model: 更新する書籍UUIDリストと評価値
         *
         *     Returns:
         *         更新結果
         */
        put: operations["change_user_data_api_books_user_data_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 閲覧状態更新
         * @description - 本を開いたとき status=open, page=0
         *     - 本を途中で閉じた時 status=pause, page=5
         *     - 本を読み終わったとき status=close, page=None
         */
        patch: operations["signal_book_status_api_books_user_data_patch"];
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * バージョン情報取得
         * @description 初期化済みか判定用
         *
         *     システムのバージョン情報と初期セットアップが完了しているかを取得します。
         */
        get: operations["get_version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * タスク一覧取得
         * @description タスク一覧を取得する
         *
         *     Args:
         *         status: ステータスフィルタ (pending, running, completed, failed)
         *         task_type: タスク種別フィルタ (load, sim_all, export等)
         *         limit: 取得件数
         *         offset: オフセット
         */
        get: operations["list_tasks_api_tasks_get"];
        put?: never;
        /**
         * タスク開始
         * @description 各種バックグラウンドタスクを開始する
         *
         *     task_type:
         *     - load: ライブラリのロード
         *     - fixmetadata: メタデータの修正
         *     - export: ライブラリのエクスポート
         *     - export_uuid: UUID指定エクスポート
         *     - sim_all: 全体の類似度計算
         *     - rule: ルール適用
         *     - thumbnail_recreate: サムネイル再作成
         *     - integrity_check: 整合性チェック
         */
        post: operations["create_background_task_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * タスク詳細取得
         * @description タスクの詳細情報を取得する
         *
         *     Args:
         *         task_id: タスクID
         */
        get: operations["get_task_api_tasks__task_id__get"];
        put?: never;
        post?: never;
        /**
         * タスクキャンセル（未実装）
         * @description タスクをキャンセルする（将来実装予定）
         *
         *     現在はステータスをcancelledに変更するのみで、
         *     実際のプロセス停止は未実装。
         */
        delete: operations["cancel_task_api_tasks__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * システム設定一覧取得
         * @description システム設定一覧を取得
         *
         *     - 管理者: 全設定を取得可能
         *     - 一般ユーザー: is_public=true の設定のみ取得可能
         *     - category パラメータでフィルタリング可能
         */
        get: operations["list_settings_api_system_settings_get"];
        put?: never;
        /**
         * 新規設定作成
         * @description 新規設定を作成（管理者のみ）
         */
        post: operations["create_setting_api_system_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 個別設定取得
         * @description 個別設定を取得
         *
         *     - 管理者: 全設定を取得可能
         *     - 一般ユーザー: is_public=true の設定のみ取得可能
         */
        get: operations["get_setting_by_key_api_system_settings__key__get"];
        /**
         * 設定更新
         * @description 設定を更新（管理者のみ）
         */
        put: operations["update_setting_api_system_settings__key__put"];
        post?: never;
        /**
         * 設定削除
         * @description 設定を削除（管理者のみ）
         */
        delete: operations["delete_setting_api_system_settings__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/settings/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 設定一括更新
         * @description 設定を一括更新（管理者のみ）
         */
        post: operations["bulk_update_settings_api_system_settings_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/settings/category/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * カテゴリ別設定取得
         * @description カテゴリ別に設定を取得（型変換済みの値）
         *
         *     - 管理者: 全設定を取得可能
         *     - 一般ユーザー: is_public=true の設定のみ取得可能
         */
        get: operations["get_settings_by_category_endpoint_api_system_settings_category__category__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/settings/all/values": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 全設定取得（型変換済み）
         * @description 全設定を取得（型変換済みの値）
         *
         *     - 管理者: 全設定を取得可能
         *     - 一般ユーザー: is_public=true の設定のみ取得可能
         */
        get: operations["get_all_settings_values_api_system_settings_all_values_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthValidateResponse */
        AuthValidateResponse: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
            /** Username */
            username: string;
            /** Is Admin */
            is_admin: boolean;
        };
        /**
         * AuthorDetail
         * @description 著者詳細レスポンス
         */
        AuthorDetail: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Isfavorite */
            isFavorite: boolean;
            /** Description */
            description: string | null;
            /** Bookcount */
            bookCount: number;
        };
        /**
         * AuthorGet
         * @description 著者取得レスポンス
         */
        AuthorGet: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Isfavorite
             * @default false
             */
            isFavorite: boolean;
            /** Bookcount */
            bookCount?: number | null;
            /** Description */
            description?: string | null;
        };
        /**
         * AuthorUpdate
         * @description 著者更新リクエスト
         */
        AuthorUpdate: {
            /** Name */
            name?: string | null;
            /** Isfavorite */
            isFavorite?: boolean | null;
            /** Description */
            description?: string | null;
        };
        /** Body_login_for_access_token_api_auth_post */
        Body_login_for_access_token_api_auth_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * BookAuthorDelete
         * @description 書籍から著者削除リクエスト
         */
        BookAuthorDelete: {
            /** Authorid */
            authorId: number;
        };
        /**
         * BookAuthorPost
         * @description 書籍への著者追加リクエスト
         */
        BookAuthorPost: {
            /** Authorid */
            authorId?: number | null;
            /** Authorname */
            authorName?: string | null;
        };
        /** BookAuthors */
        BookAuthors: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Isfavorite
             * @default false
             */
            isFavorite: boolean;
        };
        /** BookBase */
        BookBase: {
            /** Uuid */
            uuid: string;
            /** Userid */
            userId: string;
            /** Title */
            title?: string | null;
            /** Authors */
            authors: components["schemas"]["BookAuthors"][];
            publisher: components["schemas"]["BookPublisher"];
            /** Isshered */
            isShered: boolean;
            /** Chached */
            chached: boolean;
            /** Libraryid */
            libraryId: number;
            /** Genreid */
            genreId?: string | null;
            /** Tags */
            tags: components["schemas"]["BookTag"][];
            /** Size */
            size: number;
            /** Page */
            page: number;
            /** Sha1 */
            sha1: string;
            /** Importfilename */
            importFileName: string;
            /**
             * Adddate
             * Format: date-time
             */
            addDate: string;
            /**
             * Filedate
             * Format: date-time
             */
            fileDate: string;
            userData: components["schemas"]["BookUserDataBase"];
        };
        /** BookCacheCreate */
        BookCacheCreate: {
            /** Uuid */
            uuid: string;
            /** Height */
            height: number;
        };
        /**
         * BookDeleteResponse
         * @description 書籍削除レスポンス
         */
        BookDeleteResponse: {
            /** Message */
            message: string;
            /** Uuid */
            uuid: string;
        };
        /** BookGet */
        BookGet: {
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Count */
            count: number;
            /** Rows */
            rows: components["schemas"]["BookBase"][];
        };
        /** BookPublisher */
        BookPublisher: {
            /**
             * Name
             * @default
             */
            name: string | null;
            /** Id */
            id?: number | null;
        };
        /** BookPut */
        BookPut: {
            /** Uuids */
            uuids: string[];
            /** Seriesno */
            seriesNo?: number | null;
            /** Series */
            series?: string | null;
            /** Author */
            author?: string | null;
            /** Title */
            title?: string | null;
            /** Publisher */
            publisher?: string | null;
            /** Genre */
            genre?: string | null;
            /** Libraryid */
            libraryId?: number | null;
        };
        /** BookTag */
        BookTag: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * BookUpdateResponse
         * @description 書籍更新レスポンス
         */
        BookUpdateResponse: {
            /** Message */
            message: string;
            /** Updatedcount */
            updatedCount: number;
        };
        /** BookUserDataBase */
        BookUserDataBase: {
            /** Lastopendate */
            lastOpenDate?: string | null;
            /** Readtimes */
            readTimes?: number | null;
            /** Openpage */
            openPage?: number | null;
            /** Rate */
            rate?: number | null;
        };
        /** BookUserMetaDataPatch */
        BookUserMetaDataPatch: {
            /** Uuids */
            uuids: string[];
            /** Page */
            page?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "close" | "pause";
        };
        /** BookUserMetaDataPut */
        BookUserMetaDataPut: {
            /** Uuids */
            uuids: string[];
            /** Rate */
            rate?: number | null;
        };
        /** GetLibrary */
        GetLibrary: {
            /** Count */
            count: number;
            /** Name */
            name: string;
            /** Id */
            id: number;
            /** Userid */
            userId: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LibraryPatch */
        LibraryPatch: {
            /** @default load */
            state: components["schemas"]["LibraryPatchEnum"];
        };
        /**
         * LibraryPatchEnum
         * @enum {string}
         */
        LibraryPatchEnum: "export" | "load" | "export_uuid" | "fixmetadata" | "sim_all" | "rule" | "thumbnail_recreate" | "integrity_check";
        /**
         * MessageResponse
         * @description 汎用メッセージレスポンス
         */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /**
         * PatchAuthor
         * @description 著者更新リクエスト（旧形式・非推奨）
         */
        PatchAuthor: {
            /** Authorid */
            authorId: number;
            /** Isfavorite */
            isFavorite: boolean;
        };
        /**
         * SystemSettingBulkUpdateSchema
         * @description 一括更新用
         */
        SystemSettingBulkUpdateSchema: {
            /** Settings */
            settings: {
                [key: string]: string;
            };
        };
        /**
         * SystemSettingCreateSchema
         * @description 設定作成用
         */
        SystemSettingCreateSchema: {
            /** Key */
            key: string;
            /** Value */
            value: string;
            /**
             * Datatype
             * @default string
             */
            dataType: string;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Ispublic
             * @default false
             */
            isPublic: boolean;
        };
        /**
         * SystemSettingSchema
         * @description システム設定項目
         */
        SystemSettingSchema: {
            /** Key */
            key: string;
            /** Value */
            value: string;
            /** Datatype */
            dataType: string;
            /** Description */
            description?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Ispublic
             * @default false
             */
            isPublic: boolean;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Updatedby */
            updatedBy?: string | null;
        };
        /**
         * SystemSettingValueSchema
         * @description 設定値のみ（更新用）
         */
        SystemSettingValueSchema: {
            /** Value */
            value: string;
        };
        /**
         * SystemSettingsListResponse
         * @description 設定一覧レスポンス
         */
        SystemSettingsListResponse: {
            /** Settings */
            settings: components["schemas"]["SystemSettingSchema"][];
            /** Total */
            total: number;
        };
        /**
         * TagCreate
         * @description タグ作成スキーマ
         */
        TagCreate: {
            /** Name */
            name: string;
        };
        /**
         * TagResponse
         * @description タグレスポンス
         */
        TagResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * TaskCreate
         * @description タスク作成リクエスト
         */
        TaskCreate: {
            /**
             * Tasktype
             * @enum {string}
             */
            taskType: "load" | "fixmetadata" | "export" | "export_uuid" | "sim_all" | "rule" | "thumbnail_recreate" | "integrity_check";
        };
        /**
         * TaskCreateResponse
         * @description タスク作成レスポンス
         */
        TaskCreateResponse: {
            /** Status */
            status: string;
            /** Taskid */
            taskId: string;
        };
        /**
         * TaskListResponse
         * @description タスク一覧レスポンス
         */
        TaskListResponse: {
            /** Count */
            count: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Rows */
            rows: components["schemas"]["TaskSchema"][];
        };
        /**
         * TaskSchema
         * @description タスク詳細スキーマ
         */
        TaskSchema: {
            /** Id */
            id: string;
            /** Tasktype */
            taskType: string;
            /** Status */
            status: string;
            /** Progress */
            progress: number;
            /** Currentitem */
            currentItem: number;
            /** Totalitems */
            totalItems?: number | null;
            /** Currentstep */
            currentStep?: string | null;
            /** Message */
            message?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Startedat */
            startedAt?: string | null;
            /** Completedat */
            completedAt?: string | null;
            /** Userid */
            userId?: string | null;
        };
        /** TokenRFC6749Response */
        TokenRFC6749Response: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UserCurrent */
        UserCurrent: {
            /** Id */
            id: string;
            /** Token */
            token: string;
            /** Isadmin */
            isAdmin: boolean;
        };
        /**
         * UserDataUpdateResponse
         * @description ユーザーデータ更新レスポンス
         */
        UserDataUpdateResponse: {
            /** Message */
            message: string;
            /** Updatedcount */
            updatedCount: number;
        };
        /** UserGet */
        UserGet: {
            /** Id */
            id?: string | null;
            /** Isadmin */
            isAdmin: boolean;
        };
        /** UserPost */
        UserPost: {
            /** Id */
            id?: string | null;
            /** Password */
            password: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Version */
        Version: {
            /** Initialized */
            initialized: boolean;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_for_access_token_api_auth_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_api_auth_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRFC6749Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    api_auth_setup_api_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPost"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCurrent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_token_api_auth_validate_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthValidateResponse"];
                };
            };
        };
    };
    list_users_api_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGet"][];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPost"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_api_users_me__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserGet"];
                };
            };
        };
    };
    list_libraries_api_libraries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetLibrary"][];
                };
            };
        };
    };
    search_books_api_books_get: {
        parameters: {
            query?: {
                uuid?: string | null;
                fileNameLike?: string | null;
                cached?: boolean | null;
                authorLike?: string | null;
                authorIsFavorite?: boolean | null;
                titleLike?: string | null;
                fullText?: string | null;
                rate?: number | null;
                seriesId?: string | null;
                genreId?: string | null;
                libraryId?: number;
                tag?: string | null;
                state?: string | null;
                limit?: number;
                offset?: number;
                sortKey?: string;
                sortDesc?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookGet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_books_api_books_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BookPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_book_api_books__book_uuid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_book_api_books__book_uuid__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_books_cache_media_books_cache_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_media_books_duplicate_media_books_duplicate_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_books_uuid_media_books__uuid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    media_books_uuid_page_media_books__uuid___page__get: {
        parameters: {
            query?: {
                height?: number;
            };
            header?: never;
            path: {
                uuid: string;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_media_books__media_books_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCacheCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_media_library_media_library_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_tags_api_books__uuid__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 書籍UUID */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_book_tag_api_books__uuid__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 書籍UUID */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TagCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_book_tag_api_books__uuid__tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 書籍UUID */
                uuid: string;
                /** @description タグID */
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagResponse"][];
                };
            };
        };
    };
    list_authors_api_authors_get: {
        parameters: {
            query?: {
                name?: string | null;
                nameLike?: string | null;
                isFavorite?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorGet"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_author_api_authors_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchAuthor"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_author_api_authors__author_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_author_api_authors__author_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_author_by_id_api_authors__author_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                author_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_book_author_api_books__book_uuid__authors_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookAuthorPost"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_book_author_api_books__book_uuid__authors_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookAuthorDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_user_data_api_books_user_data_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BookUserMetaDataPut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserDataUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_book_status_api_books_user_data_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BookUserMetaDataPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookUserDataBase"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
        };
    };
    list_tasks_api_tasks_get: {
        parameters: {
            query?: {
                status?: string | null;
                task_type?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_background_task_api_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_api_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_api_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_settings_api_system_settings_get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSettingsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_setting_api_system_settings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemSettingCreateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSettingSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_setting_by_key_api_system_settings__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSettingSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_setting_api_system_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemSettingValueSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemSettingSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_setting_api_system_settings__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_settings_api_system_settings_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SystemSettingBulkUpdateSchema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_by_category_endpoint_api_system_settings_category__category__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_settings_values_api_system_settings_all_values_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
