version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../../:/workspace:cached
      - ../../data/:/data
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres-data:
