import createClient, { type Middleware } from "openapi-fetch";
import type { paths } from "../api"; // generated by openapi-typescript
import Cookies from "js-cookie";

let accessToken: string | undefined = undefined;

const client = createClient<paths>({
  baseUrl: import.meta.env.VITE_API_ENDPOINT,
});

const authMiddleware: Middleware = {
  async onRequest({ request }) {
    if (!accessToken) {
      accessToken = Cookies.get("accessToken");
    }

    request.headers.set("Authorization", `Bearer ${accessToken}`);
    return request;
  },
};

export async function setToken(token:string) {
  accessToken = token
}

client.use(authMiddleware);

export default client;
