# Generated by Django 3.2.9 on 2021-12-02 16:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('file_name', models.CharField(max_length=256)),
                ('file_date', models.DateTimeField()),
                ('add_date', models.DateTimeField()),
                ('page', models.IntegerField()),
                ('sha1', models.CharField(max_length=64)),
                ('size', models.BigIntegerField()),
            ],
        ),
    ]
