#!/usr/bin/env python3

import argparse
import os

def main():

    parser = argparse.ArgumentParser()

    # 引数設定
    parser.add_argument("-a")

    args = parser.parse_args()

    if args.a != None:
        if os.path.exists(f'./{args.a}'):
            print(f'App {args.a} is allredy exits')
        else:
            os.makedirs(f'./{args.a}',exist_ok=True)
            with open(f'./{args.a}/model.py', mode="w") as f:
                f.write(model_template(name=args.a))
            print(f'Make directory {args.a}')

def model_template(name):
    return f"""from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, DateTime
from sqlalchemy.orm import relationship
from mixins.database import Base, Engine


class {name.capitalize()}Model(Base):
    __tablename__ = "books"
    uuid = Column(String, primary_key=True, index=True)
    # ソフトメタデータ
    title = Column(String)
    author = Column(String)
    series = Column(String)
    series_no = Column(Integer)
    rate = Column(Integer)
    genre = Column(String)
    library = Column(String)
    publisher = Column(String)
    # ハードメタデータ
    size = Column(Integer)
    page = Column(Integer)
    add_date = Column(DateTime)
    file_date = Column(DateTime)
    import_file_name = Column(String)
    # アクティブメタデータ
    cache_date = Column(DateTime)
    open_date = Column(DateTime)
    open_count = Column(Integer)
    state = Column(String)
    """


    
if __name__ == "__main__":
    main()